version: '2'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - /docker/source/nextcloud/volumes/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=

  onlyoffice:
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    ports:
      - '8082:80'

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
      - onlyoffice
    volumes:
      - /docker/source/nextcloud/volumes/appli:/var/www/html
    restart: always
